apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: go-kafka-lab
spec:
  selector:
    app: service1
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service1-external
  namespace: go-kafka-lab
spec:
  selector:
    app: service1
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer