apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: kafka-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: your-docker-repo/service2:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: TOPIC_NAME
          value: "your-topic-name"