apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: my-kafka-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: my-kafka-microservices/service1:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: TOPIC_NAME
          value: "my-topic"